// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Howmessy.VSExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "7d202627-f08c-43f7-85aa-e727dfa5d50c";
        public const string Name = "howmessy";
        public const string Description = @"Provides a CodeLens to analyze the code metrics of a method.";
        public const string Language = "en-US";
        public const string Version = "0.5.0.0";
        public const string Author = "Takumi Yamada";
        public const string Tags = "Code Metrics, Cyclomatic Complexity, Cognitive Complexity, Maintainability Index";
    }
}
